ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_become_password: "{{ vault_enable_password }}"
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
repo_path: "/home/ipvdre/keymaker"
device_type: "layer3_switches"
